title: LD4 Discovery Affinity Group
description: Discussion of linked-data discovery in galleries, libraries, archives and museums.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
